import { AbsenceType } from '@lumicore/shared-types';

export const ABSENCE_DISPLAY: Record<AbsenceType, { code: string; label: string }> = {
  Bolnichnyi: { code: 'Б', label: 'Больничный' },
  OplachivaemyiOtpusk: { code: 'ОО', label: 'Оплачиваемый отпуск' },
  NeoplachivaemyiOtpusk: { code: 'НО', label: 'Неоплачиваемый отпуск' },
  UchebnyiOtpusk: { code: 'УО', label: 'Учебный отпуск' },
  NeoplachivaemyiUchebnyiOtpusk: { code: 'НУО', label: 'Неоплачиваемый учебный отпуск' },
  DekretnyiOtpusk: { code: 'ДО', label: 'Декретный отпуск' },
  NeoplachivaemyiDekretnyiOtpusk: { code: 'НДО', label: 'Неоплачиваемый декретный отпуск' },
  Komandirovka: { code: 'К', label: 'Командировка' },
  DenDonora: { code: 'ДД', label: 'День донора' },
  DenZdorovya: { code: 'ДЗ', label: 'День здоровья' },
  Progul: { code: 'П', label: 'Прогул' },
  OtpuskPoInvalidnosti: { code: 'ОПИ', label: 'Отпуск по инвалидности' },
  OtcovskiyOtpusk: { code: 'ОтО', label: 'Отцовский отпуск' },
  OtpuskPoBerennosti: { code: 'ОПБР', label: 'Отпуск по беременности и родам' },
  OtpuskPoUsynovleniyu: { code: 'ОПУ', label: 'Отпуск по усыновлению' },
  OtpuskPoUkhoduZaRebenkom: { code: 'ОПУР', label: 'Отпуск по уходу за ребенком' },
  VoennayaSluzhba: { code: 'ВС', label: 'Военная служба' },
  DenSudebnogRazbiratelstva: { code: 'ДСР', label: 'День судебного разбирательства' },
  VOzhidaniiRaboty: { code: 'ВОР', label: 'В ожидании работы' },
  UkhodZaBolnym: { code: 'УЗБ', label: 'Уход за больным' },
  LichnyePrichiny: { code: 'ЛП', label: 'Личные причины' },
  Obuchenie: { code: 'ОБ', label: 'Обучение' },
  ProverkaZdorovya: { code: 'ПЗ', label: 'Проверка здоровья' },
  SvobodnyiDenPoProsby: { code: 'СДР', label: 'Свободный день по просьбе работника' },
  DenPogody: { code: 'ДП', label: 'День погоды' },
  Opozdanie: { code: 'ОНР', label: 'Опоздание' },
  SvobodnyiDen: { code: 'СД', label: 'Свободный день' },
  KompensiruyushchiyOtpusk: { code: 'КО', label: 'Компенсирующий отпуск' },
};
